app:
  biblioteca:
    datasource:
      username: admin
      password: admin
      jdbc-url: jdbc:h2:mem:testdb
      driver-class: org.driver.H2
server:
  port: 8080

spring:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true

security:
  oauth2:
    client:
      scope: biblioteca
      client-id: adentis
      client-secret: adentis
